### ISSUE TITLE
Use task variable in config-task.yml

### ISSUE THREAD

**Issue by somali0128** [PatrickKish1/pulse-trade-koii-task#1]
https://github.com/PatrickKish1/pulse-trade-koii-task/blob/0b13d81748bc8f6ce9fc06f09a7f67b9f7ec7e3a/src/task/polygonService.js#L9

I see you are using .env for the PolygonService, for user they need to insert the API key themselves. To do this, add task_variable tags in config-task.yml, which can make sure your post request has the correct credentials.

For example in config-task.yml:
```
requirementsTags:
  - type: CPU
    value: "4-core"
  - type: RAM
    value: "5 GB"
  - type: STORAGE
    value: "5 GB"
  - type: TASK_VARIABLE
    value: 'POLYGON_API_KEY'
    description: 'Please enter your Polygon API key' 
```
